#!/bin/bash

# Jenkins Setup Script for IBPipeline
# This script helps configure Jenkins for GitHub integration and AWS deployment

set -e

echo "================================================"
echo "Jenkins Setup for IBPipeline CI/CD"
echo "================================================"

# Start Jenkins if not running
echo "Starting Jenkins container..."
docker-compose up -d jenkins

echo "Waiting for Jenkins to start (this may take 2-3 minutes)..."
sleep 90

# Get Jenkins initial admin password
echo ""
echo "================================================"
echo "Jenkins Initial Admin Password:"
echo "================================================"
JENKINS_PASSWORD=$(docker exec ibpipeline-jenkins cat /var/jenkins_home/secrets/initialAdminPassword 2>/dev/null || echo "Jenkins not ready yet")

if [ "$JENKINS_PASSWORD" != "Jenkins not ready yet" ]; then
    echo "$JENKINS_PASSWORD"
    echo ""
    echo "================================================"
    echo "Jenkins is ready!"
    echo "================================================"
    echo ""
    echo "Access Jenkins at: http://localhost:8082"
    echo "Use the password above for initial setup"
    echo ""
    echo "Next Steps:"
    echo "1. Open http://localhost:8082 in your browser"
    echo "2. Enter the password shown above"
    echo "3. Install suggested plugins"
    echo "4. Create admin user"
    echo "5. Follow the configuration guide below"
else
    echo "Jenkins is still starting. Run this command to get the password:"
    echo "  docker exec ibpipeline-jenkins cat /var/jenkins_home/secrets/initialAdminPassword"
fi

echo ""
echo "================================================"
echo "Jenkins Configuration Guide"
echo "================================================"
echo ""
echo "1. Install Required Plugins:"
echo "   - GitHub Integration Plugin"
echo "   - Docker Plugin"
echo "   - Docker Pipeline Plugin"
echo "   - AWS Steps Plugin"
echo "   - CloudBees AWS Credentials Plugin"
echo ""
echo "2. Add Credentials (Manage Jenkins > Credentials):"
echo "   a. GitHub Personal Access Token:"
echo "      - Kind: Secret text"
echo "      - ID: github-token"
echo "      - Secret: Your GitHub PAT"
echo ""
echo "   b. AWS Credentials:"
echo "      - Kind: AWS Credentials"
echo "      - ID: aws-credentials"
echo "      - Access Key ID: Your AWS Access Key"
echo "      - Secret Access Key: Your AWS Secret Key"
echo ""
echo "   c. AWS Account ID:"
echo "      - Kind: Secret text"
echo "      - ID: aws-account-id"
echo "      - Secret: Your AWS Account ID"
echo ""
echo "3. Create Pipeline Job:"
echo "   - New Item > Pipeline"
echo "   - Name: IBPipeline-Deploy"
echo "   - Pipeline definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: https://github.com/YOUR-USERNAME/IBDealPipeline.git"
echo "   - Credentials: Select github-token"
echo "   - Branch: */main"
echo "   - Script Path: Jenkinsfile"
echo ""
echo "4. Configure GitHub Webhook:"
echo "   a. In GitHub repo > Settings > Webhooks > Add webhook"
echo "   b. Payload URL: http://YOUR-PUBLIC-IP:8082/github-webhook/"
echo "   c. Content type: application/json"
echo "   d. Events: Just the push event"
echo ""
echo "5. Enable Build Triggers in Jenkins:"
echo "   - In your pipeline job > Configure"
echo "   - Build Triggers > GitHub hook trigger for GITScm polling"
echo ""
echo "================================================"
echo "Testing the Pipeline"
echo "================================================"
echo "1. Push a change to your main branch"
echo "2. Jenkins will automatically trigger the build"
echo "3. Monitor the build at http://localhost:8082"
echo ""
echo "================================================"
echo "Notes:"
echo "================================================"
echo "- Jenkins runs on: http://localhost:8082"
echo "- Jenkins data persisted in: jenkins_home volume"
echo "- For AWS deployment, ensure AWS credentials are configured"
echo "- For local testing, use 'Build Now' in Jenkins"
echo ""
